package services

import (
	"errors"
	"fmt"
	"time"

	"polling-system/internal/models"
	"polling-system/internal/repositories"
	"polling-system/pkg/auth"
)

// AuthService handles authentication business logic
type AuthService struct {
	userRepo         repositories.UserRepositoryInterface
	jwtSecret        string
	tokenExpiration  time.Duration
	refreshExpiration time.Duration
}

// NewAuthService creates a new auth service
func NewAuthService(userRepo repositories.UserRepositoryInterface, jwtSecret string) *AuthService {
	// Set JWT secret for the auth package
	auth.SetJWTSecret(jwtSecret)
	
	return &AuthService{
		userRepo:          userRepo,
		jwtSecret:         jwtSecret,
		tokenExpiration:   24 * time.Hour,      // 24 hours for access token
		refreshExpiration: 7 * 24 * time.Hour,  // 7 days for refresh token
	}
}

// RegisterRequest represents a registration request
type RegisterRequest struct {
	Username string          `json:"username" validate:"required,min=3,max=50"`
	Password string          `json:"password" validate:"required,min=6"`
	Role     models.UserRole `json:"role" validate:"required,oneof=admin voter"`
}

// LoginRequest represents a login request
type LoginRequest struct {
	Username string `json:"username" validate:"required"`
	Password string `json:"password" validate:"required"`
}

// AuthResponse represents an authentication response
type AuthResponse struct {
	User         *models.User `json:"user"`
	AccessToken  string       `json:"access_token"`
	RefreshToken string       `json:"refresh_token"`
	ExpiresIn    int64        `json:"expires_in"`
}

// Register registers a new user
func (s *AuthService) Register(req RegisterRequest) (*AuthResponse, error) {
	// Validate role
	if req.Role != models.RoleAdmin && req.Role != models.RoleVoter {
		return nil, errors.New("invalid role: must be 'admin' or 'voter'")
	}

	// Check if username already exists
	exists, err := s.userRepo.ExistsByUsername(req.Username)
	if err != nil {
		return nil, fmt.Errorf("failed to check username existence: %w", err)
	}
	if exists {
		return nil, errors.New("username already exists")
	}

	// Create user
	user := &models.User{
		Username: req.Username,
		Role:     req.Role,
		Status:   models.UserStatusActive,
	}

	// Hash password
	if err := user.HashPassword(req.Password); err != nil {
		return nil, fmt.Errorf("failed to hash password: %w", err)
	}

	// Save user (VoterID will be generated by BeforeCreate hook)
	if err := s.userRepo.Create(user); err != nil {
		return nil, fmt.Errorf("failed to create user: %w", err)
	}

	// Generate tokens
	accessToken, err := s.GenerateAccessToken(user)
	if err != nil {
		return nil, fmt.Errorf("failed to generate access token: %w", err)
	}

	refreshToken, err := s.GenerateRefreshToken(user)
	if err != nil {
		return nil, fmt.Errorf("failed to generate refresh token: %w", err)
	}

	return &AuthResponse{
		User:         user,
		AccessToken:  accessToken,
		RefreshToken: refreshToken,
		ExpiresIn:    int64(s.tokenExpiration.Seconds()),
	}, nil
}

// Login authenticates a user and returns tokens
func (s *AuthService) Login(req LoginRequest) (*AuthResponse, error) {
	// Find user by username
	user, err := s.userRepo.FindByUsername(req.Username)
	if err != nil {
		return nil, errors.New("invalid username or password")
	}

	// Check if user is active
	if !user.IsActive() {
		return nil, errors.New("user account is inactive")
	}

	// Verify password
	if !user.CheckPassword(req.Password) {
		return nil, errors.New("invalid username or password")
	}

	// Generate tokens
	accessToken, err := s.GenerateAccessToken(user)
	if err != nil {
		return nil, fmt.Errorf("failed to generate access token: %w", err)
	}

	refreshToken, err := s.GenerateRefreshToken(user)
	if err != nil {
		return nil, fmt.Errorf("failed to generate refresh token: %w", err)
	}

	return &AuthResponse{
		User:         user,
		AccessToken:  accessToken,
		RefreshToken: refreshToken,
		ExpiresIn:    int64(s.tokenExpiration.Seconds()),
	}, nil
}

// GenerateAccessToken generates an access token for a user
func (s *AuthService) GenerateAccessToken(user *models.User) (string, error) {
	return auth.GenerateToken(user.ID, user.Username, string(user.Role), s.tokenExpiration)
}

// GenerateRefreshToken generates a refresh token for a user
func (s *AuthService) GenerateRefreshToken(user *models.User) (string, error) {
	return auth.GenerateToken(user.ID, user.Username, string(user.Role), s.refreshExpiration)
}

// ValidateToken validates a JWT token and returns the claims
func (s *AuthService) ValidateToken(tokenString string) (*auth.Claims, error) {
	claims, err := auth.ValidateToken(tokenString)
	if err != nil {
		return nil, fmt.Errorf("invalid token: %w", err)
	}

	// Check if token is expired
	if claims.ExpiresAt != nil && claims.ExpiresAt.Before(time.Now()) {
		return nil, errors.New("token has expired")
	}

	return claims, nil
}

// RefreshToken refreshes an access token using a refresh token
func (s *AuthService) RefreshToken(refreshToken string) (*AuthResponse, error) {
	// Validate refresh token
	claims, err := s.ValidateToken(refreshToken)
	if err != nil {
		return nil, fmt.Errorf("invalid refresh token: %w", err)
	}

	// Get user from database
	user, err := s.userRepo.GetByID(claims.UserID)
	if err != nil {
		return nil, fmt.Errorf("user not found: %w", err)
	}

	// Check if user is still active
	if !user.IsActive() {
		return nil, errors.New("user account is inactive")
	}

	// Generate new tokens
	accessToken, err := s.GenerateAccessToken(user)
	if err != nil {
		return nil, fmt.Errorf("failed to generate access token: %w", err)
	}

	newRefreshToken, err := s.GenerateRefreshToken(user)
	if err != nil {
		return nil, fmt.Errorf("failed to generate refresh token: %w", err)
	}

	return &AuthResponse{
		User:         user,
		AccessToken:  accessToken,
		RefreshToken: newRefreshToken,
		ExpiresIn:    int64(s.tokenExpiration.Seconds()),
	}, nil
}

// GetUserFromToken extracts user information from a token
func (s *AuthService) GetUserFromToken(tokenString string) (*models.User, error) {
	claims, err := s.ValidateToken(tokenString)
	if err != nil {
		return nil, err
	}

	user, err := s.userRepo.GetByID(claims.UserID)
	if err != nil {
		return nil, fmt.Errorf("user not found: %w", err)
	}

	return user, nil
}

// VerifyPassword verifies a user's password
func (s *AuthService) VerifyPassword(userID uint, password string) error {
	user, err := s.userRepo.GetByID(userID)
	if err != nil {
		return fmt.Errorf("user not found: %w", err)
	}

	if !user.CheckPassword(password) {
		return errors.New("invalid password")
	}

	return nil
}